/**
 * Goal Transition Suggestions API
 *
 * GET: Fetch pending/active transition suggestions for a goal.
 * POST: Accept or dismiss a suggestion.
 *
 * Suggestions are generated by the goal-drift cron:
 * - secure_the_bag: Goal ≥90% funded → move equity to low-risk
 * - off_track_swap: Red-flagged fund → switch to better performer
 * - ltcg_harvest: Jan-March → switch off-track funds within LTCG exemption
 */

import { NextRequest, NextResponse } from 'next/server';
import { getCurrentUser } from '@/lib/auth';
import pool from '@/lib/postgres-db';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ goalId: string }> }
) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { goalId } = await params;

    // Verify goal ownership
    const goalCheck = await pool.query(
      'SELECT id FROM goals WHERE id = $1 AND user_id = $2',
      [goalId, user.id]
    );
    if (goalCheck.rows.length === 0) {
      return NextResponse.json({ success: false, error: 'Goal not found' }, { status: 404 });
    }

    const result = await pool.query(`
      SELECT id, goal_id, trigger_type,
        from_fund_name, to_fund_name, from_scheme_code, to_scheme_code,
        units_to_move, estimated_gain, tax_cost,
        projected_benefit_3y, net_benefit,
        stp_monthly_amount, stp_months,
        status, created_at
      FROM goal_transition_suggestions
      WHERE goal_id = $1 AND user_id = $2
      ORDER BY
        CASE status WHEN 'pending' THEN 0 ELSE 1 END,
        created_at DESC
      LIMIT 20
    `, [goalId, user.id]);

    const suggestions = result.rows.map((row: any) => ({
      id: row.id,
      goalId: row.goal_id,
      triggerType: row.trigger_type,
      fromFundName: row.from_fund_name || '',
      toFundName: row.to_fund_name || '',
      unitsToMove: parseFloat(row.units_to_move) || 0,
      estimatedGain: parseFloat(row.estimated_gain) || 0,
      taxCost: parseFloat(row.tax_cost) || 0,
      projectedBenefit3y: parseFloat(row.projected_benefit_3y) || 0,
      netBenefit: parseFloat(row.net_benefit) || 0,
      stpMonthlyAmount: row.stp_monthly_amount != null ? parseFloat(row.stp_monthly_amount) : null,
      stpMonths: row.stp_months,
      status: row.status,
      createdAt: row.created_at,
    }));

    return NextResponse.json({ success: true, suggestions });
  } catch (error: any) {
    console.error('Goal transitions GET error:', error);
    return NextResponse.json({ success: false, error: 'Failed to fetch transitions' }, { status: 500 });
  }
}

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ goalId: string }> }
) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { goalId } = await params;
    const body = await request.json();
    const { suggestionId, action } = body;

    if (!suggestionId || !['accept', 'dismiss'].includes(action)) {
      return NextResponse.json({ success: false, error: 'suggestionId and action (accept/dismiss) required' }, { status: 400 });
    }

    // Verify ownership and update
    const result = await pool.query(`
      UPDATE goal_transition_suggestions
      SET status = $1, acted_at = NOW()
      WHERE id = $2 AND goal_id = $3 AND user_id = $4
      RETURNING id
    `, [action === 'accept' ? 'accepted' : 'dismissed', suggestionId, goalId, user.id]);

    if (result.rows.length === 0) {
      return NextResponse.json({ success: false, error: 'Suggestion not found' }, { status: 404 });
    }

    return NextResponse.json({ success: true, message: `Suggestion ${action}ed` });
  } catch (error: any) {
    console.error('Goal transitions POST error:', error);
    return NextResponse.json({ success: false, error: 'Failed to update suggestion' }, { status: 500 });
  }
}
