-- ════════════════════════════════════════════════════════════════════
--  Migration 007: Tax-Intelligence & Goal-Transition Engine
--
--  1. User tax profile columns
--  2. LTCG buffer tracking table
--  3. Tax impact audit log
--  4. Goal transition suggestions table
--  5. Fund equity allocation classification
-- ════════════════════════════════════════════════════════════════════

-- ═══ 1. User tax profile ═══
-- Use VARCHAR instead of enum to avoid migration ordering issues
ALTER TABLE users ADD COLUMN IF NOT EXISTS income_range VARCHAR(20) DEFAULT '0-4L';
ALTER TABLE users ADD COLUMN IF NOT EXISTS occupation_type VARCHAR(20) DEFAULT 'salaried';
ALTER TABLE users ADD COLUMN IF NOT EXISTS tax_regime VARCHAR(10) DEFAULT 'new';
ALTER TABLE users ADD COLUMN IF NOT EXISTS pan_status VARCHAR(20) DEFAULT 'not_linked';

COMMENT ON COLUMN users.income_range IS 'Income bracket: 0-4L, 4-8L, 8-12L, 12-16L, 16-20L, 20-24L, 24L+';
COMMENT ON COLUMN users.occupation_type IS 'salaried, business, or professional';
COMMENT ON COLUMN users.tax_regime IS 'new (default FY2025-26) or old';
COMMENT ON COLUMN users.pan_status IS 'linked, not_linked, or exempt';
COMMENT ON COLUMN users.is_premium IS 'CFO Suite subscription (₹50/year)';

-- ═══ 2. LTCG buffer tracking ═══
-- Tracks realized Equity LTCG per financial year against ₹1.25L exemption limit.
CREATE TABLE IF NOT EXISTS ltcg_buffer (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  financial_year VARCHAR(9) NOT NULL,
  realized_ltcg DECIMAL(15,2) NOT NULL DEFAULT 0,
  exemption_limit DECIMAL(15,2) NOT NULL DEFAULT 125000,
  last_updated TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, financial_year)
);

CREATE INDEX IF NOT EXISTS idx_ltcg_user_fy ON ltcg_buffer(user_id, financial_year);

-- ═══ 3. Tax impact audit log ═══
-- Records every pre-sell/switch tax simulation for compliance audit trail.
CREATE TABLE IF NOT EXISTS tax_impact_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  holding_id UUID REFERENCES portfolio_holdings(id) ON DELETE SET NULL,
  scheme_code VARCHAR(20),
  action_type VARCHAR(20) NOT NULL,
  units DECIMAL(18,4),
  estimated_gain DECIMAL(15,2),
  gain_type VARCHAR(4),
  tax_amount DECIMAL(15,2),
  effective_rate DECIMAL(7,4),
  slab_before VARCHAR(20),
  slab_after VARCHAR(20),
  slab_push BOOLEAN DEFAULT false,
  computed_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON COLUMN tax_impact_log.action_type IS 'SELL, SWITCH, or STP';
COMMENT ON COLUMN tax_impact_log.gain_type IS 'STCG or LTCG';

-- ═══ 4. Goal transition suggestions ═══
-- Generated by cron: Secure-the-Bag (90% goals), Off-Track Swaps, LTCG Harvesting.
CREATE TABLE IF NOT EXISTS goal_transition_suggestions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  goal_id UUID NOT NULL REFERENCES goals(id) ON DELETE CASCADE,
  user_id UUID NOT NULL,
  trigger_type VARCHAR(30) NOT NULL,
  from_scheme_code VARCHAR(20),
  to_scheme_code VARCHAR(20),
  from_fund_name VARCHAR(255),
  to_fund_name VARCHAR(255),
  units_to_move DECIMAL(18,4),
  estimated_gain DECIMAL(15,2),
  tax_cost DECIMAL(15,2),
  projected_benefit_3y DECIMAL(15,2),
  net_benefit DECIMAL(15,2),
  stp_monthly_amount DECIMAL(15,2),
  stp_months INT,
  status VARCHAR(20) DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  acted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_gts_goal ON goal_transition_suggestions(goal_id);
CREATE INDEX IF NOT EXISTS idx_gts_user ON goal_transition_suggestions(user_id, status);

COMMENT ON COLUMN goal_transition_suggestions.trigger_type IS 'secure_the_bag, off_track_swap, or ltcg_harvest';
COMMENT ON COLUMN goal_transition_suggestions.status IS 'pending, accepted, or dismissed';

-- ═══ 5. Fund equity allocation ═══
-- For STCG/LTCG classification: ≥65% = equity taxation, <65% = debt taxation.
ALTER TABLE funds ADD COLUMN IF NOT EXISTS equity_allocation_pct DECIMAL(5,2);

-- Backfill equity_allocation_pct from category heuristic
UPDATE funds SET equity_allocation_pct = CASE
  WHEN category = 'Equity' THEN 100
  WHEN category = 'Debt' THEN 0
  WHEN category = 'Hybrid' AND sub_category ILIKE '%aggressive%' THEN 75
  WHEN category = 'Hybrid' AND sub_category ILIKE '%balanced%' THEN 60
  WHEN category = 'Hybrid' AND sub_category ILIKE '%conservative%' THEN 25
  WHEN category = 'Hybrid' AND sub_category ILIKE '%arbitrage%' THEN 100
  WHEN category = 'Hybrid' AND sub_category ILIKE '%equity%' THEN 70
  WHEN category = 'Hybrid' THEN 50
  WHEN category = 'Solution Oriented' THEN 70
  WHEN category = 'Other' THEN 0
  ELSE NULL
END
WHERE equity_allocation_pct IS NULL;
