/**
 * Autonomous Goal Evaluation Cron Job
 * 
 * Runs daily at 9:30 PM IST (after evening NAV update ~9 PM)
 * Pipeline: Ingest portfolio → GBM Monte Carlo → Gemini State Machine → Store flags
 * 
 * Stale-While-Revalidate: Skips users with <0.1% portfolio drift
 * Token Budget: Tracks Gemini free tier usage, batches where possible
 */

import { NextRequest, NextResponse } from 'next/server';
import pool from '@/lib/postgres-db';
import { runMonteCarlo, portfolioDrift, findRecommendedSip } from '@/lib/monte-carlo';
import { evaluateGoalWithGemini, generateMonthlyNarrative, checkTokenBudget, recordTokenUsage } from '@/lib/gemini-evaluator';
import type { GBMOutput } from '@/lib/gemini-evaluator';

const COMPLIANCE_DISCLOSURE = 'This evaluation is generated by quantitative models using historical data and Monte Carlo simulations. It does not constitute investment advice. Past performance is not indicative of future results. Please consult a SEBI-registered investment advisor before making investment decisions.';

export async function GET(request: NextRequest) {
  const secret = request.nextUrl.searchParams.get('secret');
  if (secret !== 'vmfs2024') {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const startTime = Date.now();
  const stats = {
    usersProcessed: 0,
    goalsEvaluated: 0,
    goalsSkipped: 0,
    greenFlags: 0,
    amberFlags: 0,
    redFlags: 0,
    totalTokensUsed: 0,
    monthlyNarrativeGenerated: false,
    errors: [] as string[]
  };

  const client = await pool.connect();

  try {
    // ── Step 1: Check token budget ──
    const budget = await checkTokenBudget();
    if (!budget.allowed) {
      return NextResponse.json({
        success: false,
        message: 'Daily token budget exhausted',
        budget
      });
    }

    // ── Step 2: Get all users with active goals ──
    const usersResult = await client.query(`
      SELECT DISTINCT g.user_id, u.full_name, u.email
      FROM goals g
      JOIN users u ON g.user_id = u.id
      WHERE g.is_active = true AND u.is_active = true
    `);

    const today = new Date().toISOString().split('T')[0];
    const weekStart = getWeekStart(new Date());
    const monthKey = today.substring(0, 7); // '2026-02'
    const isMonthEnd = isLastDayOfMonth(new Date());

    for (const user of usersResult.rows) {
      try {
        // ── Step 3: Get user's active goals with linked fund volatility ──
        const goalsResult = await client.query(`
          SELECT 
            g.*,
            COALESCE(AVG(fr.volatility_1y), 15) as avg_volatility,
            COALESCE(SUM(gc.amount), 0) as total_contributed
          FROM goals g
          LEFT JOIN goal_fund_links gfl ON g.id = gfl.goal_id
          LEFT JOIN fund_returns fr ON gfl.scheme_code = fr.scheme_code
          LEFT JOIN goal_contributions gc ON g.id = gc.goal_id
          WHERE g.user_id = $1 AND g.is_active = true
          GROUP BY g.id
        `, [user.user_id]);

        if (goalsResult.rows.length === 0) continue;

        const userEvaluations: { goalName: string; flag: string; successProbability: number; shortfall: number; suggestedAction: string }[] = [];

        for (const goal of goalsResult.rows) {
          // ── Step 4: Stale-While-Revalidate check ──
          const lastEval = await client.query(
            `SELECT portfolio_value_at_eval FROM goal_evaluations WHERE goal_id = $1 ORDER BY evaluated_at DESC LIMIT 1`,
            [goal.id]
          );

          const currentValue = parseFloat(goal.current_value) || 0;
          if (lastEval.rows.length > 0) {
            const lastValue = parseFloat(lastEval.rows[0].portfolio_value_at_eval) || 0;
            const drift = portfolioDrift(lastValue, currentValue);
            if (drift < 0.1) {
              // Portfolio unchanged — skip Gemini, reuse last flag
              stats.goalsSkipped++;
              continue;
            }
          }

          // ── Step 5: Run GBM Monte Carlo ──
          const now = new Date();
          const targetDate = new Date(goal.target_date);
          const monthsLeft = Math.max(1, (targetDate.getFullYear() - now.getFullYear()) * 12 + (targetDate.getMonth() - now.getMonth()));
          const volatility = parseFloat(goal.avg_volatility) || 15;
          const monthlySip = parseFloat(goal.monthly_sip) || 0;
          const targetAmount = parseFloat(goal.target_amount) || 0;
          const expectedReturn = parseFloat(goal.expected_return) || 12;
          const inflationRate = parseFloat(goal.inflation_rate) || 6;

          const mc = runMonteCarlo({
            currentValue,
            monthlySip,
            targetAmount,
            monthsLeft,
            expectedReturn,
            inflationRate,
            volatility,
            simulations: 10000
          });

          // ── Step 6: Gemini State Machine Evaluation ──
          const gbmOutput: GBMOutput = {
            goalId: goal.id,
            goalName: goal.name,
            criticality: goal.criticality,
            targetAmount,
            currentValue,
            monthlySip,
            monthsRemaining: monthsLeft,
            successProbability: mc.successProbability,
            p10: mc.p10,
            p50: mc.p50,
            p90: mc.p90,
            shortfall: mc.shortfall,
            inflatedTarget: mc.inflatedTarget,
            volatilityUsed: volatility,
            expectedReturn,
            inflationRate
          };

          const evaluation = await evaluateGoalWithGemini(gbmOutput);

          // ── Step 7: Store daily evaluation ──
          const drift = lastEval.rows.length > 0
            ? portfolioDrift(parseFloat(lastEval.rows[0].portfolio_value_at_eval) || 0, currentValue)
            : 0;

          await client.query(`
            INSERT INTO goal_evaluations (
              goal_id, user_id,
              gbm_success_probability, gbm_p10, gbm_p25, gbm_p50, gbm_p75, gbm_p90, gbm_mean, gbm_shortfall,
              gbm_volatility_used, gbm_simulations,
              portfolio_value_at_eval, monthly_sip_at_eval, months_remaining, portfolio_drift_pct,
              flag, flag_reason, suggested_action, rebalance_amount, extension_months, topup_amount, confidence_score,
              disclosure_text, gemini_tokens_used, gemini_skipped, nav_date
            ) VALUES (
              $1, $2,
              $3, $4, $5, $6, $7, $8, $9, $10,
              $11, $12,
              $13, $14, $15, $16,
              $17, $18, $19, $20, $21, $22, $23,
              $24, $25, $26, $27
            )
          `, [
            goal.id, user.user_id,
            mc.successProbability, mc.p10, mc.p25, mc.p50, mc.p75, mc.p90, mc.mean, mc.shortfall,
            volatility, 10000,
            currentValue, monthlySip, monthsLeft, drift,
            evaluation.flag, evaluation.flagReason, evaluation.suggestedAction,
            evaluation.rebalanceAmount, evaluation.extensionMonths, evaluation.topupAmount, evaluation.confidenceScore,
            COMPLIANCE_DISCLOSURE, evaluation.tokensUsed, evaluation.tokensUsed === 0, today
          ]);

          // ── Step 8: Update goal's success probability ──
          await client.query(
            `UPDATE goals SET success_probability = $1, updated_at = NOW() WHERE id = $2`,
            [mc.successProbability, goal.id]
          );

          // ── Step 9: Upsert weekly flag ──
          await client.query(`
            INSERT INTO goal_weekly_flags (goal_id, user_id, week_start, flag, flag_reason, suggested_action, success_probability)
            VALUES ($1, $2, $3, $4, $5, $6, $7)
            ON CONFLICT (goal_id, week_start) DO UPDATE SET
              flag = EXCLUDED.flag, flag_reason = EXCLUDED.flag_reason,
              suggested_action = EXCLUDED.suggested_action,
              success_probability = EXCLUDED.success_probability
          `, [goal.id, user.user_id, weekStart, evaluation.flag, evaluation.flagReason, evaluation.suggestedAction, mc.successProbability]);

          stats.totalTokensUsed += evaluation.tokensUsed;
          stats.goalsEvaluated++;
          if (evaluation.flag === 'green') stats.greenFlags++;
          else if (evaluation.flag === 'amber') stats.amberFlags++;
          else stats.redFlags++;

          userEvaluations.push({
            goalName: goal.name,
            flag: evaluation.flag,
            successProbability: mc.successProbability,
            shortfall: mc.shortfall,
            suggestedAction: evaluation.suggestedAction
          });
        }

        // ── Step 10: Monthly narrative (last day of month) ──
        if (isMonthEnd && userEvaluations.length > 0) {
          const narrative = await generateMonthlyNarrative(userEvaluations);

          await client.query(`
            INSERT INTO goal_monthly_narratives (user_id, month_key, narrative_json, summary, goals_evaluated, critical_flags, gemini_tokens_used)
            VALUES ($1, $2, $3, $4, $5, $6, $7)
            ON CONFLICT (user_id, month_key) DO UPDATE SET
              narrative_json = EXCLUDED.narrative_json, summary = EXCLUDED.summary,
              goals_evaluated = EXCLUDED.goals_evaluated, critical_flags = EXCLUDED.critical_flags,
              gemini_tokens_used = EXCLUDED.gemini_tokens_used, generated_at = NOW()
          `, [
            user.user_id, monthKey,
            JSON.stringify(narrative),
            narrative.summary,
            userEvaluations.length,
            userEvaluations.filter(e => e.flag === 'red').length,
            narrative.tokensUsed
          ]);

          stats.totalTokensUsed += narrative.tokensUsed;
          stats.monthlyNarrativeGenerated = true;
        }

        stats.usersProcessed++;
      } catch (error: any) {
        stats.errors.push(`User ${user.user_id}: ${error.message}`);
      }
    }

    // ── Record token usage ──
    await recordTokenUsage(stats.totalTokensUsed, stats.goalsEvaluated, stats.usersProcessed, stats.goalsSkipped);

    const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);

    return NextResponse.json({
      success: true,
      message: `Autonomous evaluation complete in ${elapsed}s`,
      stats,
      budget: await checkTokenBudget()
    });

  } catch (error: any) {
    console.error('Cron evaluate-goals error:', error);
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  } finally {
    client.release();
  }
}

function getWeekStart(d: Date): string {
  const date = new Date(d);
  const day = date.getDay();
  const diff = date.getDate() - day + (day === 0 ? -6 : 1); // Monday start
  date.setDate(diff);
  return date.toISOString().split('T')[0];
}

function isLastDayOfMonth(d: Date): boolean {
  const tomorrow = new Date(d);
  tomorrow.setDate(tomorrow.getDate() + 1);
  return tomorrow.getDate() === 1;
}
