/**
 * Aladdin Portfolio Recommendation — Standalone
 * POST /api/portfolio/recommend
 *
 * Accepts target amount, SIP, tenure and returns an AI-constructed portfolio.
 */

import { NextRequest, NextResponse } from 'next/server';
import { getCurrentUser } from '@/lib/auth';
import pool from '@/lib/postgres-db';
import { constructPortfolio, UserContext, GoalParams } from '@/lib/portfolio-constructor';

const COMPLIANCE_DISCLAIMER =
  'This recommendation is generated by AI models using historical fund data and quantitative metrics. ' +
  'It does not constitute investment advice. Past performance is not indicative of future results. ' +
  'Please consult a SEBI-registered investment advisor before making investment decisions.';

export async function POST(request: NextRequest) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const { targetAmount, monthlySip, tenureMonths, goalName, criticality } = body;

    // Validate required fields
    if (!targetAmount || !monthlySip || !tenureMonths) {
      return NextResponse.json(
        { error: 'targetAmount, monthlySip, and tenureMonths are required' },
        { status: 400 }
      );
    }

    if (targetAmount <= 0 || monthlySip < 500 || tenureMonths < 1) {
      return NextResponse.json(
        { error: 'Invalid values: targetAmount > 0, monthlySip ≥ 500, tenureMonths ≥ 1' },
        { status: 400 }
      );
    }

    // Fetch user profile
    const client = await pool.connect();
    let age = 30; // default
    let riskTolerance: 'conservative' | 'moderate' | 'aggressive' = 'moderate';

    try {
      const userResult = await client.query(
        `SELECT
          date_of_birth,
          risk_tolerance,
          income_range
        FROM users WHERE id = $1`,
        [user.id]
      );

      if (userResult.rows.length > 0) {
        const row = userResult.rows[0];

        // Compute age from DOB
        if (row.date_of_birth) {
          const dob = new Date(row.date_of_birth);
          const now = new Date();
          age = now.getFullYear() - dob.getFullYear();
          const m = now.getMonth() - dob.getMonth();
          if (m < 0 || (m === 0 && now.getDate() < dob.getDate())) age--;
          age = Math.max(18, Math.min(80, age));
        }

        if (row.risk_tolerance && ['conservative', 'moderate', 'aggressive'].includes(row.risk_tolerance)) {
          riskTolerance = row.risk_tolerance;
        }
      }
    } finally {
      client.release();
    }

    const userContext: UserContext = {
      userId: user.id,
      age,
      riskTolerance,
      incomeRange: '0-4L', // fetched but not used in portfolio logic yet
    };

    const goalParams: GoalParams = {
      targetAmount: parseFloat(targetAmount),
      monthlySip: parseFloat(monthlySip),
      tenureMonths: parseInt(tenureMonths),
      goalName: goalName || 'Wealth Goal',
      criticality: criticality || 'important',
    };

    // Run the Aladdin engine
    const result = await constructPortfolio(userContext, goalParams);

    return NextResponse.json({
      success: true,
      ...result,
      disclaimer: COMPLIANCE_DISCLAIMER,
    });
  } catch (error: unknown) {
    console.error('Aladdin standalone error:', error);
    return NextResponse.json(
      { error: 'Failed to generate portfolio recommendation' },
      { status: 500 }
    );
  }
}
