/**
 * Goal Evaluations API
 * GET /api/goals/evaluations — Fetch latest flags, weekly summary, monthly narrative
 */

import { NextRequest, NextResponse } from 'next/server';
import { getCurrentUser } from '@/lib/auth';
import pool from '@/lib/postgres-db';

const COMPLIANCE_DISCLOSURE = 'This evaluation is generated by quantitative models using historical data and Monte Carlo simulations. It does not constitute investment advice. Past performance is not indicative of future results. Please consult a SEBI-registered investment advisor before making investment decisions.';

export async function GET(request: NextRequest) {
  try {
    const user = await getCurrentUser();
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const client = await pool.connect();
    try {
      // Latest evaluation per goal (most recent flag)
      const flagsResult = await client.query(`
        SELECT DISTINCT ON (ge.goal_id)
          ge.goal_id, g.name as goal_name, g.icon, g.color, g.criticality,
          ge.flag, ge.flag_reason, ge.suggested_action,
          ge.rebalance_amount, ge.extension_months, ge.topup_amount,
          ge.gbm_success_probability, ge.gbm_p50, ge.gbm_shortfall,
          ge.confidence_score, ge.gemini_skipped,
          ge.evaluated_at, ge.nav_date
        FROM goal_evaluations ge
        JOIN goals g ON ge.goal_id = g.id
        WHERE ge.user_id = $1 AND g.is_active = true
        ORDER BY ge.goal_id, ge.evaluated_at DESC
      `, [user.id]);

      // Weekly flags (current week)
      const weekStart = getWeekStart(new Date());
      const weeklyResult = await client.query(`
        SELECT wf.goal_id, g.name as goal_name, wf.flag, wf.flag_reason, wf.suggested_action, wf.success_probability
        FROM goal_weekly_flags wf
        JOIN goals g ON wf.goal_id = g.id
        WHERE wf.user_id = $1 AND wf.week_start = $2
        ORDER BY
          CASE wf.flag WHEN 'red' THEN 0 WHEN 'amber' THEN 1 ELSE 2 END
      `, [user.id, weekStart]);

      // Monthly narrative (current or last month)
      const monthKey = new Date().toISOString().substring(0, 7);
      const lastMonthKey = getLastMonthKey();
      const narrativeResult = await client.query(`
        SELECT * FROM goal_monthly_narratives
        WHERE user_id = $1 AND month_key IN ($2, $3)
        ORDER BY month_key DESC LIMIT 1
      `, [user.id, monthKey, lastMonthKey]);

      // Evaluation history for trend (last 30 days, per goal)
      const trendResult = await client.query(`
        SELECT goal_id, flag, gbm_success_probability, evaluated_at::date as eval_date
        FROM goal_evaluations
        WHERE user_id = $1 AND evaluated_at > NOW() - INTERVAL '30 days'
        ORDER BY evaluated_at ASC
      `, [user.id]);

      // Build trend map
      const trendMap: Record<string, { date: string; flag: string; probability: number }[]> = {};
      for (const row of trendResult.rows) {
        if (!trendMap[row.goal_id]) trendMap[row.goal_id] = [];
        trendMap[row.goal_id].push({
          date: row.eval_date,
          flag: row.flag,
          probability: parseFloat(row.gbm_success_probability)
        });
      }

      const flags = flagsResult.rows.map(row => ({
        goalId: row.goal_id,
        goalName: row.goal_name,
        icon: row.icon,
        color: row.color,
        criticality: row.criticality,
        flag: row.flag,
        flagReason: row.flag_reason,
        suggestedAction: row.suggested_action,
        rebalanceAmount: row.rebalance_amount ? parseFloat(row.rebalance_amount) : null,
        extensionMonths: row.extension_months,
        topupAmount: row.topup_amount ? parseFloat(row.topup_amount) : null,
        successProbability: parseFloat(row.gbm_success_probability),
        projectedP50: parseFloat(row.gbm_p50),
        shortfall: parseFloat(row.gbm_shortfall),
        confidenceScore: parseFloat(row.confidence_score),
        geminiEnhanced: !row.gemini_skipped,
        evaluatedAt: row.evaluated_at,
        navDate: row.nav_date,
        trend: trendMap[row.goal_id] || []
      }));

      const weeklyFlags = weeklyResult.rows.map(row => ({
        goalId: row.goal_id,
        goalName: row.goal_name,
        flag: row.flag,
        flagReason: row.flag_reason,
        suggestedAction: row.suggested_action,
        successProbability: parseFloat(row.success_probability)
      }));

      let monthlyNarrative = null;
      if (narrativeResult.rows.length > 0) {
        const n = narrativeResult.rows[0];
        monthlyNarrative = {
          monthKey: n.month_key,
          summary: n.summary,
          narrative: n.narrative_json,
          goalsEvaluated: n.goals_evaluated,
          criticalFlags: n.critical_flags,
          generatedAt: n.generated_at
        };
      }

      return NextResponse.json({
        success: true,
        flags,
        weeklyFlags,
        monthlyNarrative,
        overallStatus: {
          totalGoals: flags.length,
          green: flags.filter(f => f.flag === 'green').length,
          amber: flags.filter(f => f.flag === 'amber').length,
          red: flags.filter(f => f.flag === 'red').length
        },
        disclosure: COMPLIANCE_DISCLOSURE
      });
    } finally {
      client.release();
    }
  } catch (error: any) {
    console.error('Evaluations fetch error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

function getWeekStart(d: Date): string {
  const date = new Date(d);
  const day = date.getDay();
  const diff = date.getDate() - day + (day === 0 ? -6 : 1);
  date.setDate(diff);
  return date.toISOString().split('T')[0];
}

function getLastMonthKey(): string {
  const d = new Date();
  d.setMonth(d.getMonth() - 1);
  return d.toISOString().substring(0, 7);
}
