/**
 * Goal Evaluations API
 * GET /api/goals/evaluations — Fetch latest flags, weekly summary, monthly narrative
 *
 * SEBI_COMPLIANCE_HOLD: Advisory evaluations disabled pending SEBI IA registration.
 * Vijay Malik Financial Services is an MFD (ARN-317605), not a SEBI-registered Investment Adviser.
 * Monte Carlo probability scores, GREEN/AMBER/RED AI flags, and suggested actions
 * constitute personalised investment advice under SEBI IA Regulations 2013 Reg 2(l).
 * Re-enable once VM Financial Advisory Pvt. Ltd. receives SEBI IA certificate.
 */

import { NextRequest, NextResponse } from 'next/server';
import { getCurrentUser } from '@/lib/auth';

export async function GET(request: NextRequest) {
  try {
    const user = await getCurrentUser();
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    // SEBI_COMPLIANCE_HOLD: Return empty evaluations.
    // All advisory outputs (flags, probability, suggested actions) are disabled.
    return NextResponse.json({
      success: true,
      flags: [],
      weeklyFlags: [],
      monthlyNarrative: null,
      overallStatus: { totalGoals: 0, green: 0, amber: 0, red: 0 },
      disclosure: 'Goal probability evaluations are temporarily unavailable while we complete SEBI Investment Adviser registration.',
    });
  } catch (error: any) {
    console.error('Evaluations fetch error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

// -----------------------------------------------------------------------------
// SEBI_COMPLIANCE_HOLD — Original evaluation logic preserved below.
// This code is unreachable. It will be re-enabled once IA registration is complete.
// -----------------------------------------------------------------------------
//
// import pool from '@/lib/postgres-db';
//
// const COMPLIANCE_DISCLOSURE = 'This evaluation is generated by quantitative models...';
//
// Original GET handler:
// 1. Fetched latest evaluation per goal (flagsResult) from goal_evaluations table
// 2. Fetched current week flags from goal_weekly_flags table
// 3. Fetched monthly narrative from goal_monthly_narratives table
// 4. Built 30-day trend map from goal_evaluations history
// 5. Returned: flags[], weeklyFlags[], monthlyNarrative, overallStatus{green,amber,red}
//
// Helper functions:
// - getWeekStart(d: Date): string — ISO week start date
// - getLastMonthKey(): string — previous month YYYY-MM key
// -----------------------------------------------------------------------------
