/**
 * Ingest parsed fund holdings into fund_top_holdings table.
 * Reads fund-holdings-parsed.json (generated by parse-fund-holdings.py)
 * and matches scheme names to AMFI scheme_codes via fuzzy search.
 *
 * Usage: npx tsx scripts/ingest-fund-holdings.ts
 */

import { Pool } from 'pg';
import * as fs from 'fs';
import * as path from 'path';

const RAILWAY_DB_URL = process.env.RAILWAY_DATABASE_URL;
if (!RAILWAY_DB_URL) {
  console.error('RAILWAY_DATABASE_URL environment variable is required');
  process.exit(1);
}

const pool = new Pool({
  connectionString: RAILWAY_DB_URL,
  ssl: { rejectUnauthorized: false },
  max: 5,
});

interface ParsedHolding {
  amc: string;
  scheme_name: string;
  holding_name: string;
  holding_isin: string;
  sector: string | null;
  weight_pct: number;
  rank: number;
}

const AS_OF_DATE = '2026-01-31';

/**
 * Normalize a scheme name for matching:
 * - lowercase, remove noise words, collapse whitespace
 */
function normalize(name: string): string {
  return name
    .toLowerCase()
    .replace(/\b(fund|scheme|plan|direct|regular|growth|idcw|dividend|option|erstwhile|known|as|of|the|and|&)\b/gi, '')
    .replace(/[-(),.]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Extract core words (length > 2) for matching
 */
function coreWords(name: string): Set<string> {
  return new Set(normalize(name).split(' ').filter(w => w.length > 2));
}

/**
 * Word-overlap similarity (intersection / min set size for asymmetric matching)
 */
function similarity(aWords: Set<string>, bWords: Set<string>): number {
  if (aWords.size === 0 || bWords.size === 0) return 0;
  let intersection = 0;
  for (const w of aWords) {
    if (bWords.has(w)) intersection++;
  }
  // Use min to allow partial matches (SEBI name is shorter than AMFI name)
  return intersection / Math.min(aWords.size, bWords.size);
}

async function main() {
  // Load parsed holdings
  const jsonPath = path.join(__dirname, 'fund-holdings-parsed.json');
  const holdings: ParsedHolding[] = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
  console.log(`Loaded ${holdings.length} holdings from ${new Set(holdings.map(h => h.scheme_name)).size} schemes`);

  // Get all Direct Growth funds from DB for matching
  const fundsResult = await pool.query(`
    SELECT scheme_code, scheme_name
    FROM funds
    WHERE plan_type = 'Direct' AND option_type = 'Growth' AND is_active = true
  `);
  const dbFunds = fundsResult.rows as { scheme_code: string; scheme_name: string }[];
  console.log(`Loaded ${dbFunds.length} Direct Growth funds from DB for matching`);

  // Group holdings by scheme
  const byScheme = new Map<string, ParsedHolding[]>();
  for (const h of holdings) {
    const key = `${h.amc}|${h.scheme_name}`;
    if (!byScheme.has(key)) byScheme.set(key, []);
    byScheme.get(key)!.push(h);
  }

  // Pre-compute word sets for all DB funds, grouped by AMC keyword
  const AMC_KEYWORDS: Record<string, string[]> = {
    SBI: ['sbi'],
    Kotak: ['kotak'],
  };

  const fundsByAmc: Record<string, { scheme_code: string; scheme_name: string; words: Set<string> }[]> = {};
  for (const [amc, keywords] of Object.entries(AMC_KEYWORDS)) {
    fundsByAmc[amc] = dbFunds
      .filter(f => keywords.some(k => f.scheme_name.toLowerCase().includes(k)))
      .map(f => ({ ...f, words: coreWords(f.scheme_name) }));
    console.log(`  ${amc} candidates: ${fundsByAmc[amc].length} funds`);
  }

  // Match each scheme to a DB fund
  let matched = 0;
  let unmatched = 0;
  let totalInserted = 0;
  const unmatchedNames: string[] = [];
  const allInserts: { schemeCode: string; h: ParsedHolding }[] = [];

  for (const [key, schemeHoldings] of byScheme) {
    const [amc, schemeName] = key.split('|');
    const candidates = fundsByAmc[amc] || [];
    const sourceWords = coreWords(schemeName);

    let bestScore = 0;
    let bestFund: { scheme_code: string; scheme_name: string } | null = null;

    for (const fund of candidates) {
      const score = similarity(sourceWords, fund.words);
      if (score > bestScore) {
        bestScore = score;
        bestFund = fund;
      }
    }

    if (!bestFund || bestScore < 0.4) {
      unmatched++;
      unmatchedNames.push(`${amc}: ${schemeName} (best=${bestScore.toFixed(2)})`);
      continue;
    }

    matched++;
    for (const h of schemeHoldings) {
      allInserts.push({ schemeCode: bestFund.scheme_code, h });
    }
  }

  console.log(`Matching done: ${matched} matched, ${unmatched} unmatched`);
  console.log(`Inserting ${allInserts.length} holdings...`);

  // Batch insert (groups of 50)
  const BATCH = 50;
  for (let i = 0; i < allInserts.length; i += BATCH) {
    const batch = allInserts.slice(i, i + BATCH);
    const values: string[] = [];
    const params: any[] = [];
    let idx = 1;

    for (const { schemeCode, h } of batch) {
      values.push(`($${idx}, $${idx+1}, $${idx+2}, $${idx+3}, $${idx+4}, $${idx+5}, $${idx+6})`);
      params.push(schemeCode, h.holding_name, h.holding_isin, h.weight_pct, h.sector, h.rank, AS_OF_DATE);
      idx += 7;
    }

    try {
      await pool.query(`
        INSERT INTO fund_top_holdings (scheme_code, holding_name, holding_isin, weight_pct, sector, rank, as_of_date)
        VALUES ${values.join(', ')}
        ON CONFLICT (scheme_code, holding_name, as_of_date) DO UPDATE SET
          holding_isin = EXCLUDED.holding_isin,
          weight_pct = EXCLUDED.weight_pct,
          sector = EXCLUDED.sector,
          rank = EXCLUDED.rank,
          fetched_at = NOW()
      `, params);
      totalInserted += batch.length;
    } catch (err: any) {
      console.error(`Batch insert error at ${i}: ${err.message}`);
      // Fallback: insert one by one
      for (const { schemeCode, h } of batch) {
        try {
          await pool.query(`
            INSERT INTO fund_top_holdings (scheme_code, holding_name, holding_isin, weight_pct, sector, rank, as_of_date)
            VALUES ($1, $2, $3, $4, $5, $6, $7)
            ON CONFLICT (scheme_code, holding_name, as_of_date) DO UPDATE SET
              holding_isin = EXCLUDED.holding_isin, weight_pct = EXCLUDED.weight_pct,
              sector = EXCLUDED.sector, rank = EXCLUDED.rank, fetched_at = NOW()
          `, [schemeCode, h.holding_name, h.holding_isin, h.weight_pct, h.sector, h.rank, AS_OF_DATE]);
          totalInserted++;
        } catch (err2: any) {
          console.error(`  Single insert error ${schemeCode}/${h.holding_name}: ${err2.message}`);
        }
      }
    }

    if ((i + BATCH) % 500 === 0) {
      console.log(`  ${Math.min(i + BATCH, allInserts.length)}/${allInserts.length} inserted`);
    }
  }

  console.log(`\nResults:`);
  console.log(`  Matched: ${matched} schemes`);
  console.log(`  Unmatched: ${unmatched} schemes`);
  console.log(`  Holdings inserted: ${totalInserted}`);

  if (unmatchedNames.length > 0 && unmatchedNames.length <= 30) {
    console.log(`\nUnmatched schemes:`);
    for (const name of unmatchedNames) {
      console.log(`  - ${name}`);
    }
  } else if (unmatchedNames.length > 30) {
    console.log(`\nFirst 30 unmatched:`);
    for (const name of unmatchedNames.slice(0, 30)) {
      console.log(`  - ${name}`);
    }
  }

  // Verify
  const countResult = await pool.query(`
    SELECT COUNT(DISTINCT scheme_code) as schemes, COUNT(*) as holdings
    FROM fund_top_holdings WHERE as_of_date = $1
  `, [AS_OF_DATE]);
  console.log(`\nDB state: ${countResult.rows[0].schemes} schemes, ${countResult.rows[0].holdings} holdings for ${AS_OF_DATE}`);

  await pool.end();
}

main().catch(err => {
  console.error('Fatal:', err);
  pool.end();
  process.exit(1);
});
