/**
 * Aladdin Portfolio Recommendation — Goal-Linked
 * POST /api/goals/{goalId}/recommend
 *
 * Derives all parameters from an existing goal and returns an AI-constructed portfolio.
 */

import { NextRequest, NextResponse } from 'next/server';
import { getCurrentUser } from '@/lib/auth';
import pool from '@/lib/postgres-db';
import { constructPortfolio, UserContext, GoalParams } from '@/lib/portfolio-constructor';

const COMPLIANCE_DISCLAIMER =
  'This recommendation is generated by AI models using historical fund data and quantitative metrics. ' +
  'It does not constitute investment advice. Past performance is not indicative of future results. ' +
  'Please consult a SEBI-registered investment advisor before making investment decisions.';

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ goalId: string }> }
) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { goalId } = await params;

    if (!goalId) {
      return NextResponse.json({ error: 'goalId is required' }, { status: 400 });
    }

    const client = await pool.connect();
    try {
      // Fetch the goal
      const goalResult = await client.query(
        `SELECT
          g.id, g.name, g.target_amount, g.target_date,
          g.monthly_sip, g.criticality, g.inflation_rate, g.expected_return,
          u.date_of_birth, u.risk_tolerance, u.income_range
        FROM goals g
        JOIN users u ON g.user_id = u.id
        WHERE g.id = $1 AND g.user_id = $2 AND g.is_active = true`,
        [goalId, user.id]
      );

      if (goalResult.rows.length === 0) {
        return NextResponse.json({ error: 'Goal not found' }, { status: 404 });
      }

      const goal = goalResult.rows[0];

      // Compute tenure in months
      const targetDate = new Date(goal.target_date);
      const now = new Date();
      const tenureMonths = Math.max(
        1,
        Math.round((targetDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24 * 30))
      );

      // Compute age from DOB
      let age = 30;
      if (goal.date_of_birth) {
        const dob = new Date(goal.date_of_birth);
        age = now.getFullYear() - dob.getFullYear();
        const m = now.getMonth() - dob.getMonth();
        if (m < 0 || (m === 0 && now.getDate() < dob.getDate())) age--;
        age = Math.max(18, Math.min(80, age));
      }

      let riskTolerance: 'conservative' | 'moderate' | 'aggressive' = 'moderate';
      if (goal.risk_tolerance && ['conservative', 'moderate', 'aggressive'].includes(goal.risk_tolerance)) {
        riskTolerance = goal.risk_tolerance;
      }

      const monthlySip = parseFloat(goal.monthly_sip) || 5000;
      if (monthlySip < 500) {
        return NextResponse.json(
          { error: 'Monthly SIP must be at least ₹500 for portfolio construction' },
          { status: 400 }
        );
      }

      const userContext: UserContext = {
        userId: user.id,
        age,
        riskTolerance,
        incomeRange: goal.income_range || '0-4L',
      };

      const goalParams: GoalParams = {
        targetAmount: parseFloat(goal.target_amount),
        monthlySip,
        tenureMonths,
        goalName: goal.name,
        criticality: goal.criticality || 'important',
      };

      // Run the Aladdin engine
      const result = await constructPortfolio(userContext, goalParams);

      return NextResponse.json({
        success: true,
        goalId,
        goalName: goal.name,
        tenureMonths,
        ...result,
        disclaimer: COMPLIANCE_DISCLAIMER,
      });
    } finally {
      client.release();
    }
  } catch (error: unknown) {
    console.error('Aladdin goal-linked error:', error);
    return NextResponse.json(
      { error: 'Failed to generate portfolio recommendation' },
      { status: 500 }
    );
  }
}
