/**
 * Aladdin Portfolio Recommendation — Goal-Linked
 * POST /api/goals/{goalId}/recommend
 *
 * Derives all parameters from an existing goal and returns an AI-constructed portfolio.
 * Fetches linked funds for dual-path auditor (KEEP_EXISTING / REBALANCE / BUILD_NEW).
 */

import { NextRequest, NextResponse } from 'next/server';
import { getCurrentUser } from '@/lib/auth';
import pool from '@/lib/postgres-db';
import { constructPortfolio, UserContext, GoalParams, LinkedFundInfo } from '@/lib/portfolio-constructor';

// Vercel Escape Hatch: Allow up to 60s execution time.
// The internal AbortController kills Gemini at 8.5s, so we always have
// headroom for the rule-based fallback to compute and return a valid 200.
export const maxDuration = 60;

const COMPLIANCE_DISCLAIMER =
  'This recommendation is generated by AI models using historical fund data and quantitative metrics. ' +
  'It does not constitute investment advice. Past performance is not indicative of future results. ' +
  'Please consult a SEBI-registered investment advisor before making investment decisions.';

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ goalId: string }> }
) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { goalId } = await params;

    if (!goalId) {
      return NextResponse.json({ error: 'goalId is required' }, { status: 400 });
    }

    const client = await pool.connect();
    try {
      // Fetch the goal
      const goalResult = await client.query(
        `SELECT
          g.id, g.name, g.target_amount, g.target_date,
          g.monthly_sip, g.criticality, g.inflation_rate, g.expected_return,
          u.date_of_birth, u.risk_tolerance, u.income_range
        FROM goals g
        JOIN users u ON g.user_id = u.id
        WHERE g.id = $1 AND g.user_id = $2 AND g.is_active = true`,
        [goalId, user.id]
      );

      if (goalResult.rows.length === 0) {
        return NextResponse.json({ error: 'Goal not found' }, { status: 404 });
      }

      const goal = goalResult.rows[0];

      // Compute tenure in months
      const targetDate = new Date(goal.target_date);
      const now = new Date();
      const tenureMonths = Math.max(
        1,
        Math.round((targetDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24 * 30))
      );

      // Compute age from DOB
      let age = 30;
      if (goal.date_of_birth) {
        const dob = new Date(goal.date_of_birth);
        age = now.getFullYear() - dob.getFullYear();
        const m = now.getMonth() - dob.getMonth();
        if (m < 0 || (m === 0 && now.getDate() < dob.getDate())) age--;
        age = Math.max(18, Math.min(80, age));
      }

      let riskTolerance: 'conservative' | 'moderate' | 'aggressive' = 'moderate';
      if (goal.risk_tolerance && ['conservative', 'moderate', 'aggressive'].includes(goal.risk_tolerance)) {
        riskTolerance = goal.risk_tolerance;
      }

      const monthlySip = parseFloat(goal.monthly_sip) || 5000;
      if (monthlySip < 500) {
        return NextResponse.json(
          { error: 'Monthly SIP must be at least 500 for portfolio construction' },
          { status: 400 }
        );
      }

      // ── Pillar 4: Fetch linked funds for dual-path auditor ──
      const linkedResult = await client.query(`
        SELECT gfl.scheme_code, gfl.allocation_pct,
               f.scheme_name as fund_name, f.category, f.sub_category,
               fr.cagr_3y, fr.sharpe_1y, fr.volatility_1y
        FROM goal_fund_links gfl
        LEFT JOIN funds f ON gfl.scheme_code = f.scheme_code
        LEFT JOIN fund_returns fr ON gfl.scheme_code = fr.scheme_code
          AND fr.calculated_date = (SELECT MAX(calculated_date) FROM fund_returns)
        WHERE gfl.goal_id = $1
      `, [goalId]);

      // Also check for deep eval health scores if available
      const deepEvalResult = await client.query(`
        SELECT fund_evaluations
        FROM goal_portfolio_evaluations
        WHERE goal_id = $1 AND user_id = $2
          AND expires_at > NOW()
        ORDER BY eval_date DESC
        LIMIT 1
      `, [goalId, user.id]);

      const healthScores: Record<string, number> = {};
      if (deepEvalResult.rows.length > 0) {
        const evals = deepEvalResult.rows[0].fund_evaluations;
        if (Array.isArray(evals)) {
          for (const e of evals) {
            if (e.scheme_code && e.health_score != null) {
              healthScores[e.scheme_code] = e.health_score;
            }
          }
        }
      }

      const linkedFunds: LinkedFundInfo[] = linkedResult.rows.map(r => ({
        schemeCode: r.scheme_code,
        fundName: r.fund_name || r.scheme_code,
        allocationPct: parseFloat(r.allocation_pct) || 100,
        category: r.category || undefined,
        subCategory: r.sub_category || undefined,
        cagr3y: r.cagr_3y ? parseFloat(r.cagr_3y) : undefined,
        sharpe1y: r.sharpe_1y ? parseFloat(r.sharpe_1y) : undefined,
        volatility1y: r.volatility_1y ? parseFloat(r.volatility_1y) : undefined,
        healthScore: healthScores[r.scheme_code] ?? undefined,
      }));

      const userContext: UserContext = {
        userId: user.id,
        age,
        riskTolerance,
        incomeRange: goal.income_range || '0-4L',
      };

      const goalParams: GoalParams = {
        targetAmount: parseFloat(goal.target_amount),
        monthlySip,
        tenureMonths,
        goalName: goal.name,
        criticality: goal.criticality || 'important',
        linkedFunds,
      };

      // Run the Aladdin engine
      const result = await constructPortfolio(userContext, goalParams);

      return NextResponse.json({
        success: true,
        goalId,
        goalName: goal.name,
        tenureMonths,
        ...result,
        disclaimer: COMPLIANCE_DISCLAIMER,
      });
    } finally {
      client.release();
    }
  } catch (error: unknown) {
    console.error('Aladdin goal-linked error:', error);
    return NextResponse.json(
      { error: 'Failed to generate portfolio recommendation' },
      { status: 500 }
    );
  }
}
